version: '2'
services:
  web-api:
    build: .
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:3.4"
    command:
      --smallfiles
    ports:
      - 27017
